apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: code-with-quarkus-hola-cqni
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: code-with-quarkus-hola-cqni
    app.kubernetes.io/part-of: annyong
  name: code-with-quarkus-hola-cqni
  namespace: rh-ee-chernand-tenant
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: code-with-quarkus-hola-cqni
status:
  loadBalancer: {}
